### ISSUE TITLE
[CH3] 3.5.3 형식 추론 

### ISSUE THREAD

**Issue by JinseoPark-bd** [BanditBool2/ReadingRecord#14]
- 자바 컴파일러는 람다 표현식이 사용된 콘텍스트(대상 형식)를 이용해서 함수형 인터페이스를 추론할 수 있습니다.
- 즉, 함수 디스크립터를 알 수 있으므로 람다의 시그니처를 추론할 수 있습니다. 
- 파라미터 형식을 추론할 수 있어서 개발자 입장에서는 생략이 가능합니다.
```java
// 1)
Comparator<Apple> c =
   (Apple a1,  Apple a2) -> a1. getWeight().compareTo(a2.getWeight()); //형식 추론 하지 않음 (명시적이여서 읽기는 더 편하다)
// 2)
Comparator<Apple> c =
   ( a1,  a2 ) -> a1. getWeight().compareTo(a2.getWeight()); // 형식을 추론함 (생략해서 코드가 더 간결)
```
어떤 방법이 좋은지 정해진 것은 없다고 합니다. 

1. 꼭 생략해서 써야할 때가 있을까요?
2. 평소에 어떤 코드를 더 선호 하시나요?

**Comment by hanbonghun** [comment]
1. 꼭 생략해야 하는 경우는 잘 떠오르지 않지만 파라미터가 적고 구현이 단순하다면 파라미터를 생략해줌으로써 코드를 짧고 단순하게 만들 수 있어 좋을 거 같아요.

2. 저는 구현이 단순하거나 일회성으로 쓰이는 경우에는 파라미터 형식을 생략하고, 그 외에는 파라미터 형식을 명시적으로 쓰는 편인데요 파라미터가 많거나 형식이 복잡할 때 파라미터 형식을 작성해주면 코드 의도를 명확히 전달할 수 있어서 협업할 때 좋은 점이 많다고 생각합니다.
