### ISSUE TITLE
[Ch4] 4.3 데이터 계산 시점에 있어 컬렉션와 스트림의 차이 

### ISSUE THREAD

**Issue by hanbonghun** [BanditBool2/ReadingRecord#21]
p144에 데이터를 언제 계산하느냐가 가장 큰 차이이고, 컬렉션은 현재 자료구조가 포함하는 모든 값을 메모리에 저장하기 때문에 모든 요소가 컬렉션에 추가하기 전에 계산되어야 한다고 적혀 있습니다. 

모든 요소가 추가하기 전에 계산되어야 한다는 게 구체적으로 무슨 말인가요 ?? 예를 들어서 설명해주시면 감사하겠습니다.

**Comment by kkambbak** [comment]
해당 요소가 컬렉션에서 사용될 때 계산되는 것이 아니라, 컬렉션에 추가되기 전에 미리 계산해야 한다는 것을 의미합니다.

만약 2부터 n까지의 수 중에서 소수를 찾는 코드를 짠다면,
컬렉션에서는 2부터 n까지의 수를 담은 리스트를 만들어 놓은 상태에서 작업을 시작해야합니다.
따라서, for문으로 2부터 n까지(모든 요소가 추가하기전에) 1씩 증가(계산되어야함)을 통해 List를 생성해야겠죠.

반면, 스트림은 IntStream.rangeClosed(2,n).~~~으로 stream이 실행될 때 2부터 n까지의 값들을 만들기 시작할 것입니다. 

스트림은 데이터 소스의 요소들을 한 번에 한 개씩 처리하는 반면에, 
컬렉션은 모든 요소를 메모리에 미리 저장해 놓고 처리한다는 것입니다.

이러한 차이로 인해, 스트림은 매우 큰 데이터 소스를 처리할 때 메모리 사용량을 최소화하고, 처리 속도를 높일 수 있는 장점이 있습니다.
