### ISSUE TITLE
[Ch4] 4.3 스트림과 컬렉션 차이

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#22]
스트림(내부반복) 과 컬렉션(외부반복)은 데이터를 언제 계산하느냐가 가장 큰 차이라고 하며, 책에서는 개념적인 부분으로 설명하고 있습니다.

작업을 병렬적으로 처리하거나 더 최적화된 다양한 순서로 처리하는 스트림(내부반복)을 활용하는 것이 더 좋은 방법이라고 생각이 되는데, 
컬렉션(외부반복)을 사용했을 때 좋은 예시도 알면 이 둘의 차이를 정확하게 이해할 수 있을 것 같아서,,

**컬렉션(외부반복)을 사용할 때 더 좋은 예시가 있을까요?**

**Comment by kkambbak** [comment]
간단한 반복문의 경우에는 대부분의 상황에서 **컬렉션을 통한 외부 반복**이 Stream을 통한 내부반복보다 훨씬 빠릅니다.


경험을 공유해드리자면, 코딩테스트를 볼때 정도가 있을거 같아요

for문으로 0.01~0.03ms가 걸리는 것이, stream을 통해 풀면 2.00ms에서 3.xx ms까지 걸리는 것을 보았습니다.

**Comment by JinseoPark-bd** [comment]
속도적인 측면에 있어서는 외부반복이 내부반복보다 빠릅니다.
특히 primitive type(int 등)의 데이터를 처리할 때는 외부반복의 속도가 훨씬 빠릅니다. 
primitive type은 스택에 저장되어 있어서 단순 인덱스 기반으로 도는 외부반복은 직접적으로 접근이 가능하지만 스트림은 스택에 접근하기 위해 boxing이 필요하여 이 과정중에 오버헤드가 많이 발생하기 때문에 내부반복의 속도가 많이 느려집니다.
하지만, wrapped type 데이터의 경우는 힙에 저장되어있어서 간접적으로 참조하게되어 비용이 커지게 때문에 외부반복과 내부반복의 속도 차이가 줄어듭니다. 
결과적으로 primitive type의 데이터를 순회할 때는 외부반복을 사용하는 것이 더 낫다고 생각합니다.
