### ISSUE TITLE
[Ch 5] 5.8.5 함수로 무한 스트림 만들기

### ISSUE THREAD

**Issue by sohhhyeeun** [BanditBool2/ReadingRecord#24]
- 책에서 ' iterate는 요청할 때마다 값을 생산할 수 있으며 끝이 없으므로 무한 스트림을 만들고 이러한 스트림을 언바운드 스트림이라고 표현한다. ' 라고 나와있는데 그럼 무한 스트림은 언바운드 스트림과 종속 관계인걸까요?
- 추가로 위와 같은 특징이 스트림과 컬렉션의 가장 큰 차이점이라고 나와있는데 글로만 설명되어 있어 이해하기에 어려움이 있는데 이해를 도울 수 있는 예시가 있을까요?

**Comment by hanbonghun** [comment]
- 저는 무한 스트림을 언바운디드 스트림의 한 종류라고 생각했습니다.
무한 스트림은 원소의 개수가 무한대인 스트림을 의미하고 언바운드 스트림은 스트림의 크기가 사전에 정해져 있지 않아져 무한대로 스트림을 생성할 수도 있고(무한스트림) 그러지 않을 수도 있다 라고 이해했습니다. 

- 컬렉션과 스트림의 주요 차이 중 하나가 데이터 처리 방식인데요, 컬렉션은 컬렉션의 모든 요소를 메모리에 올려두고 사용하는 방식이고 스트림은 접근하는 요소만들 메모리에 올려 처리하고 파이프라이닝을 하는 방식입니다. 
- 
예를 들어 크지 않은 범위 내에서 스트림으로 데이터를 처리하는 것을 컬렉션으로 표현할 수는 있겠지만, 그 범위가 무한이 된다면 컬렉션은 무한대 크기으 요소를 메모리에 올려야 하는 거니까 이는 스트림에서만 가능합니다. 

``` java
// 1부터 무한대까지의 수를 생성하는 무한 스트림
Stream<Integer> infiniteStream = Stream.iterate(1, n -> n + 1);

// 1부터 무한대까지의 수를 컬렉션에 저장
List<Integer> collection = new ArrayList<>(); 
for(int i=1; ; i++) collection.add(i)  //불가능

// 무한 스트림에서 10개의 원소만 가져와 출력하는 코드
infiniteStream.limit(10).forEach(System.out::println);
```
예를 들어 위 코드에서처럼 무한 스트림을 만들고, 해당 스트림에서 일부를 출력할 수 있지만, 컬렉션의 경우 무한대 크기의 요소를 컬렉션에 담는 것이 불가능 합니다.
