### ISSUE TITLE
[Ch6] 6.2.4 collect와 reduce의 차이 

### ISSUE THREAD

**Issue by hanbonghun** [BanditBool2/ReadingRecord#30]
p207에 collect와 reduce의 차이에 관해 설명하는 내용이 있는데요, 

> collect 메서드는 결과를 누적하는 컨테이너를 바꾸도록 설계된 메서드인 반면 reduce는 두 값을 하나로 도출하는 불변형 연산이라는 점에서 의미론적인 문제가 일어난다. 

에서 컨테이너를 바꾼다는 것과 불변형 연산이 무엇인지 설명해주시면 감사하겠습니다.

**Comment by parkchaewon18** [comment]
컨테이너는 컬렉션 데이터 타입으로 여러 개의 값을 저장하고 관리하는 데 사용됩니다. 리스트나 집합, 딕셔너리 등이 모두 컨테이너의 한 종류 입니다.

컨테이너를 바꾼다는 것은 새로운 요소를 추가하거나 기존 요소를 삭제하는 등의 작업으로 컨테이너의 상태를 변경하는 것을 의미합니다.

불변형 연산은 객체의 상태를 변경하지 않고, 새로운 객체를 생성하여 결과를 반환하는 연산을 의미합니다. 

collect 메서드는 누적 작업을 위해 컨테이너를 사용하는데, 스트림의 각 요소를 수집하여 컨테이너에 쌓는 메서드라고 할 수 있습니다. 예를 들어, 스트림에서 문자열 요소만 수집하여 List<String> 컬렉션에 저장할 때, collect 메서드는 스트림의 각 요소를 처리하여 결과를 누적하는 컨테이너(예: List, Set, Map 등)를 바꾸는 동작을 수행합니다.

반면에 reduce는 스트림의 모든 요소를 하나의 값으로 도출하는 불변형 연산입니다. 이때 reduce 메서드는 스트림의 요소를 조합하여 하나의 값으로 축소하는 작업을 수행하며, 이 과정에서 스트림의 요소를 변경하지 않고 새로운 값을 계속해서 생성합니다. 예를 들어, 스트림에서 요소의 합계를 구하는 reduce 연산은 스트림의 모든 요소를 더한 하나의 값을 반환합니다.  

**따라서, collect 메서드는 컨테이너의 상태를 변경하는 작업을 수행하며 결과를 누적하는 반면, reduce 메서드는 불변형 연산을 수행하여 두 값을 하나로 도출하는 데 사용된다는 것에서 차이가 있습니다.**


- 추가로 이해하시는 데 도움이 될 것 같아 collect 메서드와 reduce 메서드를 비교할 수 있는 코드 예시를 적었습니다.

```java
        **// collect 메서드 사용 예시**
        List<String> words = Arrays.asList("hello", "world", "java", "stream");
        List<String> filteredWords = words.stream()
                                          .filter(word -> word.length() > 4)
                                          .collect(Collectors.toList());
        System.out.println(filteredWords); // [world, stream]
        
        **// reduce 메서드 사용 예시**
        List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5);
        int sum = numbers.stream()
                         .reduce(0, Integer::sum);
        System.out.println(sum); // 15
```  

위 예시에서 collect 메서드는 스트림에서 길이가 4 이상인 단어를 필터링하여 List<String> 컬렉션에 저장합니다. 
그러나 reduce 메서드는 스트림의 모든 요소를 더하여 하나의 값을 반환합니다.
