### ISSUE TITLE
[Ch 7] 7.2.2 포크/조인 프레임워크를 제대로 사용하는 방법

### ISSUE THREAD

**Issue by sohhhyeeun** [BanditBool2/ReadingRecord#34]
왼쪽 작업과 오른쪽 작업 모두 fork 메서드를 호출하는 것보다 한쪽 작업에는 compute를 호출하는 것이 효율적이라고 나와있는데 조금은 추상적으로 다가와서 이해를 도울 수 있는 구체적인 예시가 있을까요?

**Comment by hanbonghun** [comment]
내용이 어려워서 저도 맞는지는 모르겠지만 제가 이해한대로 말씀드려 보겠습니다.
 
우선 fork는 추가적인 스레드 공간을 만들어서 나뉘어진 작업을 수행하는 걸로 이해를 했습니다. 
그러면 처음에 스레드1이라는 공간에서 left, right라는 작업으로 나누고, left를 포크해서 새로운 스레드에서 작업을 하게 하는 거니까 right는 굳이 새로운 스레드를 만들지 않고, 기존 스레드에서 작업을 수행하게 하는 게 낫다 라고 이해를 했어요.

예를 들어 한 집에서 살던 부부가 이혼을 했을 때 둘다 따로 집구하는 거보다는 한명만 집구하고 다른 한명은 기존 집에서 사는 것처럼....
