### ISSUE TITLE
[Ch 7] 7.3.1 분할 과정

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#36]
p. 264 

Spliterator 특성에 
Sliterator는 characteristics라는 추상 메서드도 정의하고, Characteristics 메서드는 Spliterator 자체의 특성 집합을 포함하는 int를 반환합니다. Sliterator를 이용하는 프로그램은 이들 특성을 참고해서 Sliterator를 더 잘 제어하고 최적화할 수 있습니다.

책에서는 Sliterator의 특성 정보를 보여주며 설명을 하고 있는데, 일부 특성은 컬렉터(Collectors)와 개념상 비슷함에도 다른 방식으로 정의되어 있다고 합니다. 이 부분 이해를 돕기 위해 조금 더 자세하게 설명해 주실 수 있을까요?

즉, **Spliterator의 Characteristics 옵션은 Collectors의 것과 동일하지 않다**는 부분이 잘 와닿지가 않습니다

**Comment by JinseoPark-bd** [comment]
추가적인 정보로 
Characteristics메서드는 Spliterator객체의 모든 특성값의 합을 int로 반환합니다.  예시로는

- List Spliterator : ORDERED, SIZED, SUBSIZED
- Set Spliterator : DISTINCT, SIZED
- IntStream.of Spliterator : IMMUTABLE, ORDERED, SIZED, SUBSIZED
- IntStream.generate Spliterator : IMMUTABLE

```java
// Set의 경우 DISTINCT=1, SIZED=64 의 합인 65를 반환합니다.
new HashSet().spliterator().characteristics();  // 65
// List의 경우 ORDERED=16, SIZED=64, SUBSIZED=16384 의 합인 16464를 반환합니다.
new ArrayList().spliterator().characteristics(); // 16464
```
Spliterator의 각 특성은 hasCharacteristics메서드를 통해 확인 할 수 있습니다.
