### ISSUE TITLE
[Ch 7] 7.2.2 fork join 프레임워크 제대로 사용하기

### ISSUE THREAD

**Issue by kkambbak** [BanditBool2/ReadingRecord#38]
260p
2번째 구문에서
- 서브태스크에 fork 메서드를 호출해서 ForkJoinPool의 일정을 조절 할 수 있다. 왼쪽 작업과 오른 쪽 작업 모두에 fork 메서드를 호출하는 것이 자연스러울 것 같지만, 한쪽 작업에는 fork를 호출하는 것보다는 compute를 호출하는 것이 효율적이다.
**그러면 두 서브태스크의 한 태스크에는 같은 스레드를 재사용할 수 있으므로** 풀에서 불필요한 태스크를 할당하는 오버헤드를 피할 수 있다.

**그러면 두 서브태스크의 한 태스크에는 같은 스레드를 재사용할 수 있으므로** 
->같은 스레드를 재사용할 수 있다는 게 잘 와닿지가 않습니다. 어떤 식으로 이해하셨는지 궁금합니다.

**Comment by hanbonghun** [comment]
https://github.com/BanditBool2/ReadingRecord/issues/34#issue-1665825945
이 질문에 대한 답에서 말했듯, 저는 스레드1이라는 하나의 스레드 내에서 작업을 a,b로 분할했다면 a라는 대상은fork를 통해 스레드2에서 작업을 수행하게 하고, 남은 b작업은 굳이 새 스레드를 만들지 않고 스레드1에서 작업을 이어나가도록 해서 스레드를 재사용한다 라고 이해했습니다. 근데 내용이 어려워서 맞는 내용인지는 모르겠습니다. 틀린 부분 있으면 지적 부탁드립니다.

**Comment by hanbonghun** [comment]
> 아 fork()를 2번 실행하면 쓰레드가 총 3개가 있게 되는거니까, fork()를 한번만 사용해서 쓰레드를 총 2개를 사용하게 만든다는 말씀이신거죠? 이해했습니다... 생각보다 간단한 내용이었네요.

넵 근데 이는 한 번의 연산을 기준으로 말씀 드린 거고, 재귀적으로 fork 와 compute가 수행되니까 전체적으로 봤을 때는 2개보다 많은 스레드를 사용하게 된다고 이해했습니다.
