### ISSUE TITLE
[Ch 3] 3.5.4 지역 변수 제약의 필요성 

### ISSUE THREAD

**Issue by hanbonghun** [BanditBool2/ReadingRecord#39]
p113의 **지역 변수의 제약** 항목의 내용입니다. 

> 람다에서 지역 변수에 바로 접근할 수 있다는 가정하에 람다가 스레드에서 실행된다면 변수를 할당한 스레드가 사라져서 변수 할당이 해제되었는데도 람다를 실행하는 스레드에서는 해당 변수에 접근하려 할 수 있다.

라는 내용이고, 이로 인해 발생할 수 있는 문제 때문에 지역 변수의 제약이 있다고 설명하고 있는데요,  

변수를 할당한 스레드가 사라지고 할당이 해제되었다는 게 구체적으로 어떤 상황인건가요?? 간단한 코드로 예시를 들어주시면 감사하겠습니다.

**Comment by parkchaewon18** [comment]
지역 변수의 제약 항목 중 "변수를 할당한 스레드가 사라져서 변수 할당이 해제되었는데도 람다를 실행하는 스레드에서는 해당 변수에 접근하려 할 수 있다"는 내용은 람다 표현식이 스레드에서 실행될 때, 람다 표현식이 참조하는 외부 변수의 상태가 변경되었을 경우 발생할 수 있는 문제를 가리킵니다. 이는 람다 표현식이 클로저(closure)라는 개념을 가지고 있기 때문입니다. 이슈 올리신 내용 뒷 장에 '클로저'의 개념에 관해 설명하고 있는데, 클로저는 함수의 비지역 변수를 자유롭게 참조할 수 있는 함수의 인스턴스를 가리킵니다. 클로저 외부에 정의된 변수의 값에 접근하고, 값을 바꿀 수 있습니다. 또한, 람다가 정의된 메서드의 지역 변숫값은 스택에 존재하므로 자신을 정의한 스레드와 생존을 같이 해야 하며 따라서 지역 변수는 final 변수여야 합니다.


```
public class LambdaExample {

    public static void main(String[] args) {
        int count = 0; // 지역 변수 count

        Runnable runnable = () -> {
            for (int i = 0; i < 5; i++) {
                System.out.println("Count: " + count); // 람다 표현식에서 count 변수 참조
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };

        new Thread(runnable).start(); // 스레드 실행

        // 메인 스레드에서 count 변수 변경
        try {
            Thread.sleep(2000);
            count = 10;
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

```
위 코드에서 runnable 람다 표현식에서 count 변수를 참조하고 있습니다. **그리고 메인 스레드에서 count 변수의 값을 변경하고 있습니다. 이 경우, 람다 표현식이 실행 중인 스레드와 메인 스레드가 서로 다른 스레드이기 때문에, 메인 스레드에서 count 변수의 값이 변경되더라도 람다 표현식에서는 변경된 값을 참조할 수 없습니다.** 이는 람다 표현식이 해당 변수를 "캡처"하여 클로저로서 사용하고 있기 때문입니다. 따라서, 람다 표현식이 실행되는 동안 해당 변수의 상태가 변경되면 예상치 못한 동작이 발생할 수 있습니다.
