### ISSUE TITLE
[Ch1] 1.5 디폴트 메서드

### ISSUE THREAD

**Issue by sohhhyeeun** [BanditBool2/ReadingRecord#4]
디폴트 메소드가 선언되는 인터페이스와 추상 클래스의 구체적인 차이는 무엇일까요?

**Comment by kkambbak** [comment]
자바 8이전에는 인터페이스는 메소드 구현부를 가질 수 없습니다.

8 이후에는 디폴트 메소드가 생기면서 가질 수 있게 되었습니다.

---

인터페이스 VS 추상 클래스

- 둘 다 인스턴스화가 불가능하고, 구현부가 있는, 없는 메소드를 모두 가질 수 있다는 점에서 유사함.

- 인터페이스에서 모든 변수는 기본적으로 public static final 이고, 모든 메소드는 public abstract 인 반면
추상클래스에서는 static 이나 final 이 아닌 필드를 지정할 수 있고, public, protected, private 메소드를 가질 수 있다.

- 인터페이스를 구현하는 어떤 클래스들은 다른 인터페이스들과 함께 만들 수 있으나, 추상클래스는 다중상속 불가


아래 글을 참조 하였습니다. https://yaboong.github.io/java/2018/09/25/interface-vs-abstract-in-java8/

**Comment by hanbonghun** [comment]
#### 디폴트메서드 : 추상 메서드의 기본 구현을 제공하는 메서드
- 인터페이스를 구현하는 클래스에서는 인터페이스의 모든 메서드를 구현해야함
- 인터페이스 설계를 잘 하더라도 변경이 필요할 때가 생기는데, 해당 인터페이스를 구현한 모든 클래스에서 변경된 메서드를 구현해주어야 하는 문제 발생
- 이런 문제를 해결하기 위해 **JAVA8**부터는 **디폴트 메서드** 기능을 추가해서 인터페이스 내 추상 메서드의 기본적 구현을 제공하여 해당 인터페이스를 구현하는 클래스에서 추가로 구현할 필요가 없음

```java
interface MyInterface{
  void method(); 
  default void newMethod(){} // 새로운 메서드를 추가하더라도 기존에 MyInterface를 구현한 클래스를 변경하지 않아도 됨
}
````

#### 디폴트 메서드가 기존의 메서드와 이름이 중복되어 충돌하는 경우 해결하는 규칙 
1. 여러 인터페이스의 디폴트 메서드 간의 충돌
  - 인터페이스를 구현한 클래스에서 디폴트 메서드를 오버라이딩 해야 함 
2. 디폴트 메서드와 조상 클래스의 메서드 간의 충돌
  - 조상 클래스의 메서드가 상속되고, 디폴트 메서드는 무시된다. 

참고 : JAVA의 정석 p401
