### ISSUE TITLE
[Ch5] 5.52 스트림 연산

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#41]
책 p.175

**map, filter** 등은 입력 스트림에서 각 요소를 받아 0 또는 결과를 출력 스트림으로 보냅니다. 따라서 이들은 보통 **상태가 없는 연산**입니다.

**sorted이나 distinct** 같은 연산은 연산을 수행하는 데 필요한 저장소 크기는 정해져있지 않아서 데이터 스트림의 크기가 크거나 무한이라면 문제가 생길 수도 있습니다. 이러한 연산을 **내부 상태를 갖는 연산**이라고 언급하고 있는데, 

상태가 있고 없고의 연산 개념이 헷갈려서 이해를 돕기 위한 예시로 설명해 주실 수 있을까요?

**Comment by kkambbak** [comment]
### 내부상태를 갖는 연산
- distinct()는 중복 요소를 제거하는 메서드입니다. 중복제거를 위해 내부적으로 Set을 사용하여, 이전 요소들을 저장하고 있습니다.
- sorted()는 요소를 정렬하는 메서드입니다. 정렬을 위해 내부적으로 요소들이 버퍼에 추가되어 있습니다.

여기서 요소들을 저장한다와 버퍼에 추가한다는 같은 말입니다. 
정렬을 한다면, 정렬을 하는 중간중간 상태를 저장하는 공간이 있다는 뜻입니다.

### 내부상태가 필요 없는 연산
- 이제 반대로, map과 filter는 괄호안의 메서드에 따라 처리된 '결과'만을 내보내는 메서드입니다. 
결과를 내보내는데에 필요한 중간과정을 가지고 있을 필요가 없는 메서드들인거죠. 

예시보다는 직관적인 설명이 좀 더 설명하기 쉬운거 같아서 이렇게 설명드렸습니다.
