### ISSUE TITLE
[Ch8] 8.4.2 계수

### ISSUE THREAD

**Issue by JinseoPark-bd** [BanditBool2/ReadingRecord#43]
>  ConcurrentHashMap 클래스는 맵의 매핑 개수를 반환하는 mappingCount 메서드를 제공한다. 기존의 size는 메서드 대신 새 코드에서는 int를 반환하는 mappingCount 메서드를 사용하는 것이 좋다. 그래야 매핑의 개수가 int의 범위를 넘어서는 이후의 상황을 대처할 수 있기 때문이다.

라고 합니다.  이 3줄 전부 이해가 안되긴 하는데 , 여기서 맵의 매핑 개수가 왜 필요한지. 그리고 매핑의 개수가 int의 범위를 넘어서는 이후의 상황을 왜 대처해야 하는지 궁금합니다.

**Comment by sohhhyeeun** [comment]
size 메서드는 int형이기 때문에 long형인 mappingCount를 사용함으로써 매핑의 개수가 int의 범위를 넘어서는 이후의 상황을 대처합니다.
