### ISSUE TITLE
[Ch9] 9.2.2 람다로 객체지향 디자인 패턴 리팩터링하기

### ISSUE THREAD

**Issue by JinseoPark-bd** [BanditBool2/ReadingRecord#45]
### 9.2.2 템플릿 메서드 
305p 기존의 템플릿 메서드를 람다로 리팩터링하기 입니다.
- 템플릿 메서드 패턴 : 알고리즘의 개요를 제시한 다음에 알고리즘의 일부를 고칠 수 있는 유연함을 제공해야 할 때 사용 
 -> 다른 관점에서 보면 동일한 기능을 상위 클래스에서 정의하면서 확장/변화가 필요한 부분만 서브 클래스에서 구현할 수 있도록 한다.

```java
abstract class OnlineBanking {
   public void processCustomer(int id) {
       Customer c = Database.getCustomerWithId(id);
       makeCustomerHappy(c);
   }
   abstract void makeCustomerHappy (Customer c);
}
```
람다 표현식으로 리팩터링
```java
public void processCustomer(int id, Consumer<Customer> makeCustomerHappy) {
    Customer c = Database.getCustomerWithId(id);
    makeCustomerHappy.accept(c);
}

new OnlineBankingLambda().processCustomer(1337, (Customer c) -> System.out.println("Hello " + c.getName());
```
- _**여기서 makeCustomerHappy를 인수로 추가한 것과 갑자기 makeCustomerHappy.accept(c)가 나온 부분이 이해가 되지 않습니다. 설명 도와 주시면 감사하겠습니다**._

**Comment by kkambbak** [comment]
제가 책을 읽으며 찾아보고 메모해놨던 내용입니다. 혹시 도움이 될까 해서 남겨봅니다.

### 템플릿 메서드 패턴
세부 메소드 abstract로 남겨놓고, 자식클래스에서 override해서 사용하는 패턴.
세부 메소드를 각각 구체화해서 생성한 상속받은 클래스들을 만드는 것.
메인 메소드에서는 override한 세부메소드를 이용하여 각각의 기능을 구현한다.

예를 들어, 데이터베이스에서 id를 가져오는 것까지는 동일하고(메인메서드에서 처리)
결제 방식이 여러가지가 있다면 이를 세부 메소드에서 처리하게끔 abstract로 남겨놓고, 각각의 클래스로 만들어 처리하는 것.

### 리팩토링
메인메소드에 파라미터로 `Consumer<>` 형식을 갖는 인수를 추가하여 이를 람다표현식으로 구현한다. 

그러면 세부 메소드를 따로 클래스로 만들지 않아도 됨.

## ->갑자기 `makeCustomerHappy.accept(c)`가 나온 이유?

`makeCustomerHappy`는 `Consumer<>`형식입니다. 

Consumer<>는 `void accept(T t)` 메서드를 가지고 있습니다.

`Customer c = Database.getCustomerWithId(id);`

  `makeCustomerHappy.accept(c);`

Customer 객체 c를 makeCustomerHappy 메서드에서 소비하는 겁니다. 
accept가 어떻게 구현되는지는 클래스들에 따라 다르겠죠.

조금이라도 이해가 안되시는 부분이 있다면 댓글로 남겨주세요.
