### ISSUE TITLE
[Ch9] 9.2.5 팩토리 패턴

### ISSUE THREAD

**Issue by kkambbak** [BanditBool2/ReadingRecord#46]
p311~ p312에서 

팩토리 패턴으로 클래스의 이름을 파라미터로 받아서, loan, stock, bond 클래스의 인스턴스를 생성하고 있습니다.

`Supplier<Product> loanSupplier = Loan::new` 처럼, 생성자를 메서드 참조로 접근하고, 
이를 static에서 `Map<String, Supplier<Product>>`에 put하여 관리하는 예제가 있습니다.

- 왜 static에서 관리하도록 한걸까요? 예제라서 단순히 이렇게 표현할 수 있다 라고 보여주기 위한 걸까요?
실제로 사용한다면 ProductFactory 클래스를 따로 만들어서 사용하는걸까요?

- 그때그때 생성자를 호출하는 것이 낫지 않을까라고 생각했었는데,
Supplier<T> 인터페이스는 .get()메서드의 Lazy Evaluation으로 동일하게 작동함을 다시한번 알게 되어 남깁니다.
책에서는 이걸 당연히 안다고 생각하고 생략한거 같더라고요. 저처럼 까먹었을 분들을 위해 남겨둡니다.

**Comment by parkchaewon18** [comment]
static으로 Map을 관리하는 이유는 생성한 인스턴스를 계속 유지하기 위해서입니다. 만약 static이 아닌 인스턴스 변수로 Map을 관리한다면, 해당 인스턴스가 Garbage Collection될 때 생성한 인스턴스들도 함께 사라집니다. 그러므로 static으로 Map을 관리하여 어디서든지 생성한 인스턴스들을 참조할 수 있도록 하는 것이 좋습니다.

실제로 사용한다면, ProductFactory 클래스를 따로 만들어서 사용할 수도 있지만, 그렇게 하지 않고도 다른 클래스에서도 쉽게 접근해서 사용할 수 있도록 하기 위해서 static으로 관리하는 것입니다. 만약 해당 클래스가 다른 클래스에서 사용되지 않고 독립적으로 사용된다면, 별도의 클래스를 만들 필요 없이 Factory 패턴을 구현한 클래스 내에 Map을 관리하는 것이 더 효율적일 수 있습니다.

Supplier 인터페이스는 .get()메서드의 Lazy Evaluation으로 동일하게 작동하여 불필요한 인스턴스 생성을 방지하고, 필요한 시점에만 인스턴스를 생성하여 메모리를 효율적으로 사용할 수 있습니다. 다시 한번 상기시켜주셔서 감사합니다 👊
