### ISSUE TITLE
[Ch 8] 8.4 개선된  ConcurrentHashMap

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#48]
책 p.290
ConcurrentHashMap의 동기화 처리 방식에서
Map 인터페이스를 구현한 3가지 구현체인 **HashMap, Hashtable, ConcurrentHashMap의 차이**에 대해 궁금합니다.

**Comment by sohhhyeeun** [comment]
- HashMap
1. key와 value에 null을 허용합니다.
2. 동기화를 보장하지 않습니다.

- Hashtable
1.  key와 value에 null을 허용하지 않습니다.
2. 동기화를 보장합니다.

- ConcurrentHashMap
1.  key와 value에 null을 허용하지 않습니다.
2. 동기화를 보장합니다.

참고 자료에 각각의 예시 코드와 장점과 단점이 간략하게 잘 나와있어 확인해 보셔도 좋을 것 같습니다!
참고 : https://tecoble.techcourse.co.kr/post/2021-11-26-hashmap-hashtable-concurrenthashmap/
