### ISSUE TITLE
[Ch 9] 9.2.4 의무 체인_람다 표현식 사용

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#49]
책 p.310

작업 처리 객체의 체인(동작 체인 등)을 만들 때는 의무 체인 패턴 을 사용하며, 이 패턴은 함수 체인(함수 조합) 과 비슷하다고 책에서 설명하고 있습니다. 
작업 처리 객체를 Function<String, String>, 더 정확히 표현하자면 UnaryOperator<String> 형식의 인스턴스로 표현할 수 있다고 하는데, 이러한 람다 표현식을 조합하는 방법에 있어 유사점이 정확하게 와닿지가 않아 조금 더 부가적인 설명해 주실 수 있을까요?

**Comment by sohhhyeeun** [comment]
채원님의 질문을 잘 이해했는지 모르겠지만
저는 함수 체인(함수 조합)을 활용해 람다 표현식을 조합하면 의무 체인과 같은 방식으로 사용이 가능해진다고 이해했습니다..!
