### ISSUE TITLE
[Ch 10] 10.4.1 jOOQ

### ISSUE THREAD

**Issue by JinseoPark-bd** [BanditBool2/ReadingRecord#50]
- jOOQ는 DSL을 가장 광범위하게 사용하며, SQL질의를 작성하고 실행하는데 필요한 멋진 DSL을 제공하는 자바 라이브러리이다.
- 자바 컴파일러가 복잡한 SQL 구문의 형식을 확인할 수 있으면 역공학 프로세스 제품이 생성한 정보를 기반으로 데이터베이스 스키마를 탐색할 수 있습니다.
- 스트림 API와 조합해 사용가능하다.

```sql
SELECT * FROM BOOK
WHERE BOOK.PUBLISHED_IN = 2016
ORDER BY BOOK>TITLE
```
```java
create.selectFrom(BOOK) 
   .where(BOOK.PUBLISHED_IN.eq(2016))
   .orderBy(BOOK.TITLE)
```
---
Q) 1. 강의 시간에 한 번 QueryDSL을 사용했던 적은 있는데 jOOQ는 처음 알게 되었습니다. QueryDSL이 더 좋은 건가요??
2. 스프링부트에서 개발할 때 JPA를 사용하는데 JPA를 쓰면 jOOQ는 사용할 일이 없는 건가요?

**Comment by kkambbak** [comment]
용도의 차이인 것 같습니다. 성능에서는 큰 차이가 없다고 합니다.
JPA를 사용하다보면 가아끔 복잡한 쿼리나 ORM으로 해결할 수없는 쿼리가 등장했을 때 도입을 고려해봄직하다고 합니다.

QueryDSL은 타입 안정성을 제공하고, jOOQ는 SQL에 직접적으로 접근할 수있는 높은 유연성을 제공. 이라고는 하는데 직접 써봐야 알거 같긴하네요..
