### ISSUE TITLE
[CH 10] 10.3.3 람다 표현식을 이용한 함수 시퀀싱

### ISSUE THREAD

**Issue by sohhhyeeun** [BanditBool2/ReadingRecord#51]
DSL 형식의 장점으로는
1. 메서드 체인 패턴처럼 플루언트 방식으로 거래 주문을 정의할 수 있다.
2. 중첩 함수 형식처럼 다양한 람다 표현식의 중첩 수준과 비슷하게 도메인 객체의 계층 구조를 유지한다.
을 말할 수 있습니다.

이때 플루언트 방식이 익숙하지 않아 그런데 플루언트 방식으로 정의했을 때의 구체적인 장점은 무엇이 있을까요?

**Comment by JinseoPark-bd** [comment]
플루언트 방식(플루언트 API)은 메소드 체인 패턴에 상당 부분 기반한 객체 지향 API 설계 메소드입니다. 메소드 체인 패턴과 같이 메소드를 이어서 호출하여 단일 명령문으로 형성할 수 있는 기술입니다.  [예제 10-6]과 같이 플루언트 방식은 일반 메소드와는 다르게 메소드들이 객체를 반환합니다.

플루언트 방식의 목적은 소스 코드의 가독성을 산문과 유사하게 만드는 것이라고 합니다.  도메인 개발에 있어서 개발자 뿐만 아니라 비전문가들도 쉽게 이해할 수 있게 간단하게 기술하는 것입니다. 목적에서도 알 수 있듯이 최대 장점은 가독성이라고 생각합니다.

**Comment by kkambbak** [comment]
책에서 말하는 형식이라는게 인터페이스를 번역한것이지 않나 싶습니다.

플루언트 인터페이스(Fluent Interface)는 메소드 체이닝에 상당 부분 기반한 객체 지향 API 설계메소드이며, 가독성을 좋게 만드는 것이 목적이다.

- 이를 위해 각 메서드는 호출된 객체 자체를 반환하는 형식으로 구현됨.
- 각 메서드 호출 결과를 바로 다음 메서드의 인자로 전달하여, 코드를 간결하게 작성.

https://en.wikipedia.org/wiki/Fluent_interface


아래는 책에서 나온 예제입니다.

```java
Order order = forCustomer("BigBank")
        .buy(80).stock("IBM").on("NYSE").at(125.00)
        .sell(50).stock("GOOGLE").on("NASDAQ").at(375.00)
        .end();
```

스트림에서 사용하는 것과 비슷하게, 메서드들을 연결해서 사용하는 것이 플루언트 형식입니다.

이렇게 사용하기 위해 미리 정의해놓은 인터페이스나 클래스를 설계할 때 각 메서드는 호출된 객체 자체를 반환하는 형식으로 구현하고요.

메서드체이닝은 이미 예은님이 실제로 사용하고 계셨을 내용입니다.
