### ISSUE TITLE
[Ch10] 10.3.2 더미메소드?

### ISSUE THREAD

**Issue by kkambbak** [BanditBool2/ReadingRecord#52]
p344 중첩된 함수 이용에서 나오는 구절입니다.

인수의 의미가 이름이 아니라 위치에 의해 정의되었다.
NestedFunctionOrderBuilder의 at(), on()메서드에서 했던 것처럼 
인수의 역할을 확실하게 만드는 여러 더미 메서드를 이용해 마지막 문제를 조금 완화할 수 있다.

```java
public class NestedFunctionOrderBuilder {
...
  public static double at(double price) {
    return price;
  }

  public static Stock stock(String symbol, String market) {
    Stock stock = new Stock();
    stock.setSymbol(symbol);
    stock.setMarket(market);
    return stock;
  }

  public static String on(String market) {
    return market;
  }
...
}
```

```java
//main
public void nestedFunction() {
    Order order = order("BigBank",
        buy(80,
            stock("IBM", on("NYSE")),
            at(125.00)),
        sell(50,
            stock("GOOGLE", on("NASDAQ")),
            at(375.00))
    );
```

더미메소드를 왜 쓰는지는 대략 알거 같은데
굳이 이렇게 써야할까요? 

인수로 market은 그렇다쳐도  price는 그냥 long이나 double으로 넘겨줄 수 있지 않을까요?

그리고 "인수의 의미가 이름이 아니라 위치에 의해 정의되었다" 라는 구절도 좀 이해가 가지 않습니다.

어떻게 이 문제를 완화했다는 걸까요?

**Comment by parkchaewon18** [comment]
**더미 메서드(dummy method)는 코드의 가독성을 높이고, 인수의 의미를 명확하게 만들기 위해 사용됩니다.** 

예를 들어, at() 메서드는 가격을 나타내는 데 사용되며, stock() 메서드는 주식을 식별하는 데 사용됩니다. 이러한 메서드를 사용하여 코드를 읽는 사람이 인수가 어떤 역할을 하는지 쉽게 이해할 수 있습니다.

인수의 의미가 이름이 아니라 위치에 의해 정의된다는 문구는 함수나 메서드가 인수의 이름이 아니라 위치에 따라 인수를 구분한다는 의미입니다. 이것은 함수 호출에서 인수의 위치가 중요하다는 것을 의미합니다. 예를 들어, at(20.00)에서 20.00은 가격을 나타내는 인수이며, 이 값은 위치에 따라 at() 메서드가 인수를 해석합니다.

더미 메서드를 사용하여 인수의 역할을 명확하게 만드는 것은 선택사항이지만, 코드를 더 읽기 쉽고 이해하기 쉽게 만듭니다. 그리고 이를 통해 코드 유지보수성이 높아집니다.

마지막으로, 인수로 price가 long이나 double로 넘겨줄 수 있다는 것은 맞지만, 그 경우에는 가격이라는 것을 명확히 표현하지 않으므로 가독성이 떨어질 수 있습니다. 따라서 at() 메서드를 사용하여 가격을 명시적으로 지정하는 것이 좋습니다.
