### ISSUE TITLE
[Ch11] 11.3. 도메인 모델에 Optional을 사용했을 때 데이터를 직렬화할 수 없는 이유

### ISSUE THREAD

**Issue by JinseoPark-bd** [BanditBool2/ReadingRecord#56]
p.377에서
> Optional 클래스는 필드 형식으로 사용할 것을 가정하지 않았으므로 직렬화 인터페이스를 구현하지 않는다. 따라서 우리 도메인 모델에 Optional을 사용한다면 직렬화 모델을 사용하는 도구나 프레임워크에서 문제가 생길 수 있다.

라고 합니다.  그럼에도 Optional을 사용하는 것이 바람직하다고 하는데 어떤 경우에 문제가 생기는지 모르겠습니다.  설명해주시면 감사하겠습니다.

**Comment by sohhhyeeun** [comment]
기본적으로 Optional은 직렬화를 지원하지 않아서 캐시나 메세지큐 등과 연동할 때 문제가 발생할 수 있다고 합니다. Jackson처럼 라이브러리에 Optional이 있을 경우 값을 wrap, unwrap 하도록 지원해주기도 하지만 해당 라이브러리의 스펙을 파악해야 한다는 점 등에서 오히려 불편함을 느낄 수 있습니다.
따라서 Optional은 반환 타입으로만 사용해야 합니다.

참고 : https://mangkyu.tistory.com/203
