### ISSUE TITLE
[CH11] 11.3.3 flatMap으로 Optional 객체 연결

### ISSUE THREAD

**Issue by sohhhyeeun** [BanditBool2/ReadingRecord#57]
마지막에 'map 메서드 였다면 Optional 내부에 다른 Optional 그리고 그 내부에 삼각형이 저장되겠지만 flatMap 메서드 덕분에 이차원 Optional이 하나의 삼각형을 포함하는 하나의 Optional로 바뀐다.'라고 나와있는 부분은 결국 각각의 메서드를 적용함에 있어 반환값에 차이가 발생한다고 이해하면 될까요?

**Comment by parkchaewon18** [comment]
네, 저도 그렇게 이해했습니다.

'map' 메서드는 함수를 적용하여 새로운 값을 감싸는 Optional을 반환하고, 만약 해당 값이 이미 Optional이라면, 내부 Optional을 유지합니다. 즉, 'map' 메서드를 두 번 적용하면, 내부에 Optional이 중첩된 Optional이 반환됩니다.

하지만 'flatMap' 메서드는 함수를 적용하여 반환된 값을 바로 감싸는 Optional로 만듭니다. 만약 반환 값이 Optional이면, 이를 풀어서 다시 하나의 Optional 안에 넣습니다. 따라서 'flatMap' 메서드를 사용하면 중첩된 Optional을 평평하게 펴서 하나의 Optional 안에 포함시킬 수 있습니다.

따라서, 'map' 메서드를 사용하면 중첩된 Optional을 유지하고, 'flatMap' 메서드를 사용하면 중첩된 Optional을 플랫하게 만들어서 하나의 Optional로 반환합니다. 이 차이점은 코드에서 반환 값이 Optional인 경우 중요하게 작용할 수 있습니다.
