### ISSUE TITLE
[CH1] 1.3.1 메서드와 람다를 일급 시민으로

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#6]
함수형 프로그래밍으로 다가서며, 자바 8에서는 더 이상 메서드가 이급값이 아닌 일급값으로 취급하여, 메서드 참조를 만들어 전달할 수 있게 되었습니다. 이렇게 메서드를 값으로 취급하는 것이 프로그래머가 활용할 수 있는 도구가 더 다양해진다는 의미로 이어지는데, 이 이유가 명확하게 와닿지 않습니다. 이해를 돕기 위한 사례나 부가 설명해 주실 수 있을까요?

**Comment by hanbonghun** [comment]
함수형 프로그래밍에서는 함수를 값으로 다루는 것이 중요한데, 이는 함수를 다른 함수의 인자로 전달하거나 함수의 결과값으로 반환할 수 있다는 의미합니다. 자바8 이후, 메서드 참조를 통해 이러한 기능을 할 수 있게 되었습니다.

메서드를 값으로 취급할 때 프로그래머가 활용 가능한 도구가 더 다양해진다는 것의 의미는, 함수를 더욱 자유롭게 조합하고 활용할 수 있도록 만들어준다는 것입니다. 이러한 기능은 코드의 가독성과 유지보수성, 그리고 재사용성을 높여줍니다. 

예를 들어, 자바 8의 스트림(Stream) API에서는 많은 메서드들이 함수를 인자로 받습니다. 이때, 메서드 참조를 사용하여 간단하게 함수를 전달할 수 있습니다. 예를 들어, 다음은 리스트에서 문자열 길이가 5 이하인 문자열만 필터링하여 출력하는 예시입니다.

```java
List<String> names = Arrays.asList("John", "Jane", "Tom", "Steve");
names.stream()
     .filter(str -> str.length() <= 5) // 람다식을 사용한 필터링
     .forEach(str -> System.out.println(str)); // 람다식을 사용한 출력

// 메서드 참조를 사용한 필터링과 출력
names.stream()
     .filter(Main::isShortName) // 메서드 참조를 사용한 필터링
     .forEach(System.out::println); // 메서드 참조를 사용한 출력

// isShortName 메서드 정의
public static boolean isShortName(String str) {
    return str.length() <= 5;
}
```

위 코드에서는 filter 메서드와 forEach 메서드에서 함수를 인자로 받고 있습니다. 람다식을 사용하면서 함수를 직접 구현할 수도 있지만, isShortName 메서드를 구현하고 이를 메서드 참조로 전달하는 것도 가능합니다. 이렇게 메서드를 값으로 취급하여 전달하면, 코드의 가독성과 유지보수성이 높아집니다.
