### ISSUE TITLE
[CH2] 2.3.1 익명 클래스에 대해

### ISSUE THREAD

**Issue by parkchaewon18** [BanditBool2/ReadingRecord#8]
**Q. 동적파라미터화를 이해하기 위해 알고 있으면 좋은 익명 클래스 문법에 대해 설명해주세요**

객체 자신이 동작이 되고 그 동작을 파라미터화 시킴으로써 좀 더 간결한 코드를 작성할 수 있는 **동작 파라미터화**는 각 항목에 적용할 동작을 분리할 수 있는다는 강점을 가지고 있습니다. 

익명 객체를 이용하여 파라미터화를 하는 **익명 클래스**는 가독성을 떨어뜨리고 유지 보수가 어렵다는 단점을 가지고 있지만, 동적 파라미터화를 이해하기에는 좋은 문법이라고 생각하였습니다.

이 익명 클래스 문법에 대한 설명이 책에는 부족한 것 같아 부가 설명해 주실 수 있을까요?

**Comment by hanbonghun** [comment]
익명 클래스는 다른 클래스의 인스턴스를 생성하면서 동시에 구현하는 클래스로, 다음과 같은 문법을 가집니다.

```java
new SuperType(constructor arguments) {
    // anonymous class body
}
```
위 문법에서 SuperType은 익명 클래스가 구현하는 클래스나 인터페이스를 나타내며, constructor arguments는 생성자에 전달되는 인자들입니다. 익명 클래스의 몸체는 {} 안에 작성되며, 클래스가 구현해야 하는 메서드를 오버라이드하여 구현합니다.

익명 클래스를 자주 사용하는 예로 Comparator 인터페이스를 구현하는 익명 클래스가 있는데요 다음과 같은 방식으로 코드를 작성하여 정렬 방식을 위한 익명 클래스를 sort함수의 인자로 생성합니다.

```java
List<String> names = Arrays.asList("Apple", "Banana", "Orange");
Collections.sort(names, new Comparator<String>() {
    public int compare(String s1, String s2) {
        return s1.compareTo(s2);
    }
});
```

위 코드에서 new Comparator<String>() { ... } 부분이 익명 클래스를 생성하는 부분입니다. 익명 클래스는 Comparator 인터페이스를 구현하며, compare 메서드를 오버라이드하여 구현합니다. 익명 클래스의 몸체에서는 두 문자열을 비교하는 동작을 수행합니다.
